CREATE TABLE IF NOT EXISTS mpa (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    description varchar,
    CONSTRAINT mpa_name UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS genre (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(25),
    CONSTRAINT genre_name UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS film (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar NOT NULL,
    realease_date date NOT NULL,
    duration int8 NOT NULL,
    mpa_ID integer REFERENCES mpa (ID)
    );


CREATE TABLE IF NOT EXISTS film_genre (
    film_ID integer REFERENCES film (ID),
    genre_ID integer REFERENCES genre (ID),
    CONSTRAINT no_repeat_film_genre UNIQUE (film_ID ,genre_ID)
    );


CREATE TABLE IF NOT EXISTS users (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    login varchar NOT NULL,
    name varchar,
    birthday date
    );

CREATE TABLE IF NOT EXISTS user_like
(
    film_ID integer REFERENCES film (ID),
    user_ID integer REFERENCES users (ID)
    );

CREATE TABLE IF NOT EXISTS friends (
    user_ID integer REFERENCES users (ID),
    friend_ID integer REFERENCES users (ID),
    status varchar default 'false'
    );

